In [5]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [6]:
np.version.version

'1.18.1'

In [101]:
a = np.random.random((2,3,5))

In [153]:
a

array([[[0.7614986 , 0.45233804, 0.51851771, 0.38311128, 0.24433541],
        [0.54165859, 0.4473517 , 0.84457095, 0.0801512 , 0.85902381],
        [0.97122331, 0.76209301, 0.14296221, 0.42864006, 0.63438679]],

       [[0.7479465 , 0.12842186, 0.25555672, 0.44644943, 0.37462937],
        [0.42035797, 0.31216649, 0.08779383, 0.9226329 , 0.49127311],
        [0.33352432, 0.7638433 , 0.45665749, 0.47952696, 0.16835634]]])

In [154]:
b = np.ones((5,2,3))

In [155]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [156]:
np.array_equal(a,b)

False

In [157]:
b.shape

(5, 2, 3)

In [158]:
b.shape = (2,3,5)

In [159]:
c = b
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [160]:
d = a + c
d

array([[[1.7614986 , 1.45233804, 1.51851771, 1.38311128, 1.24433541],
        [1.54165859, 1.4473517 , 1.84457095, 1.0801512 , 1.85902381],
        [1.97122331, 1.76209301, 1.14296221, 1.42864006, 1.63438679]],

       [[1.7479465 , 1.12842186, 1.25555672, 1.44644943, 1.37462937],
        [1.42035797, 1.31216649, 1.08779383, 1.9226329 , 1.49127311],
        [1.33352432, 1.7638433 , 1.45665749, 1.47952696, 1.16835634]]])

In [161]:
print(a)
print(d)

[[[0.7614986  0.45233804 0.51851771 0.38311128 0.24433541]
  [0.54165859 0.4473517  0.84457095 0.0801512  0.85902381]
  [0.97122331 0.76209301 0.14296221 0.42864006 0.63438679]]

 [[0.7479465  0.12842186 0.25555672 0.44644943 0.37462937]
  [0.42035797 0.31216649 0.08779383 0.9226329  0.49127311]
  [0.33352432 0.7638433  0.45665749 0.47952696 0.16835634]]]
[[[1.7614986  1.45233804 1.51851771 1.38311128 1.24433541]
  [1.54165859 1.4473517  1.84457095 1.0801512  1.85902381]
  [1.97122331 1.76209301 1.14296221 1.42864006 1.63438679]]

 [[1.7479465  1.12842186 1.25555672 1.44644943 1.37462937]
  [1.42035797 1.31216649 1.08779383 1.9226329  1.49127311]
  [1.33352432 1.7638433  1.45665749 1.47952696 1.16835634]]]


In [162]:
e = a * c
e

array([[[0.7614986 , 0.45233804, 0.51851771, 0.38311128, 0.24433541],
        [0.54165859, 0.4473517 , 0.84457095, 0.0801512 , 0.85902381],
        [0.97122331, 0.76209301, 0.14296221, 0.42864006, 0.63438679]],

       [[0.7479465 , 0.12842186, 0.25555672, 0.44644943, 0.37462937],
        [0.42035797, 0.31216649, 0.08779383, 0.9226329 , 0.49127311],
        [0.33352432, 0.7638433 , 0.45665749, 0.47952696, 0.16835634]]])

In [163]:
d_max = np.amax(d)
print(d_max)

d_min = np.amin(d)
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9712233103885026
1.080151203464991
1.4820333087172817


In [171]:
f = np.empty([2,3,5])
f

array([[[0.7614986 , 0.45233804, 0.51851771, 0.38311128, 0.24433541],
        [0.54165859, 0.4473517 , 0.84457095, 0.0801512 , 0.85902381],
        [0.97122331, 0.76209301, 0.14296221, 0.42864006, 0.63438679]],

       [[0.7479465 , 0.12842186, 0.25555672, 0.44644943, 0.37462937],
        [0.42035797, 0.31216649, 0.08779383, 0.9226329 , 0.49127311],
        [0.33352432, 0.7638433 , 0.45665749, 0.47952696, 0.16835634]]])

In [178]:
for i in np.nditer(d):
    if i == d_min:
        f = 0
    elif [(i>d_min) & (i<d_mean)]:
        f = 25
    elif i==d_mean:
        f = 50
    elif [(i < d_max) & (i > d_mean)]:
        f = 75
    elif i == d_max:
        f = 100

In [179]:
print(f)

25
